@startuml
package "model" {
    class "Product" as model.Product <<V,Orchid>> {
        +Id: int
        +Price: int
    }
}

package "repo" {
    class "ProductRepo" as repo.ProductRepo <<V,Orchid>> {
        +Get(id int): Product
    }
}

package "service" {
    class "ProductService" as service.ProductService <<V,Orchid>> {
        +Exist(id int) bool
    }
}

main --> service.ProductService
service.ProductService --> repo.ProductRepo
repo.ProductRepo --> model.Product
@enduml
