// Code generated by MockGen. DO NOT EDIT.
// Source: dao.go

// Package mock_main is a generated GoMock package.
package mock_main

import (
	"github.com/care-1040/di-sample/src"
	"github.com/golang/mock/gomock"
	"reflect"
)

// MockTodoDaoInterface is a mock of TodoDaoInterface interface
type MockTodoDaoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTodoDaoInterfaceMockRecorder
}

// MockTodoDaoInterfaceMockRecorder is the mock recorder for MockTodoDaoInterface
type MockTodoDaoInterfaceMockRecorder struct {
	mock *MockTodoDaoInterface
}

// NewMockTodoDaoInterface creates a new mock instance
func NewMockTodoDaoInterface(ctrl *gomock.Controller) *MockTodoDaoInterface {
	mock := &MockTodoDaoInterface{ctrl: ctrl}
	mock.recorder = &MockTodoDaoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTodoDaoInterface) EXPECT() *MockTodoDaoInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockTodoDaoInterface) Get(id int) src.Todo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(src.Todo)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockTodoDaoInterfaceMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTodoDaoInterface)(nil).Get), id)
}
